# 👩‍💻 Tensor Operations, Gradients, and GPU Practice

## 📋 Overview
In this lab, you will gain hands-on experience with fundamental PyTorch components that form the backbone of deep learning workflows. You'll create and manipulate tensors, compute gradients automatically, and leverage GPU acceleration to speed up your computations. By the end of this lab, you'll understand how these elements work together to enable efficient deep learning model development and training.

- Create and manipulate tensors using various PyTorch operations
- Compute gradients automatically using PyTorch's autograd functionality
- Move computations between CPU and GPU to observe performance differences
- Implement basic tensor reshaping and broadcasting techniques

In [1]:
import torch
import time

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


Required tools/setup:

- Python 3.6 or later
- PyTorch installed (1.7 or later recommended)
- Access to a GPU is beneficial but not required

## Task 1: Create Tensors and Perform Matrix Operations
**Context:** In deep learning, you frequently need to create matrices and vectors to represent data and model parameters. Matrix operations form the foundation of neural network computations.

**Steps:**

1. Create a 3x3 matrix tensor using `torch.tensor()`
    - Use a nested list structure to define your matrix values
    - Consider using floating point values for better compatibility

2. Create a 3x1 vector tensor

    - Make sure the dimensions are compatible for matrix multiplication

3. Perform matrix multiplication using `torch.mm()`

    - Why does `torch.mm()` require specific dimension compatibility? What would happen if dimensions don't match?
    - How is this different from element-wise multiplication?

4. Print the result and verify the shape is as expected (should be 3x1)

In [1]:
# Your code for creating matrices and performing operations

import torch

# --- Create a 3x3 matrix ---
A = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

# --- Create a 3x1 vector ---
v = torch.tensor([
    [1.0],
    [2.0],
    [3.0]
])

# --- Matrix multiplication ---
result = torch.mm(A, v)

print("Matrix A:\n", A)
print("Vector v:\n", v)
print("A * v =\n", result)
print("Result shape:", result.shape)

Matrix A:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Vector v:
 tensor([[1.],
        [2.],
        [3.]])
A * v =
 tensor([[14.],
        [32.],
        [50.]])
Result shape: torch.Size([3, 1])


🔍 Why does torch.mm() require dimension compatibility?

Because matrix multiplication is defined only when:
(A_{m\times n})\cdot (B_{n\times p})=C_{m\times p}
If dimensions don’t match, PyTorch raises an error — the operation is mathematically undefined.


🔍 How is this different from element‑wise multiplication?

- torch.mm() → matrix multiplication
- A * v → element‑wise multiplication (requires same shape or broadcastable shapes)

## Task 2: Reshape and Broadcast Tensors
**Context:** When working with neural networks, you'll often need to reshape data or perform operations between tensors of different shapes. PyTorch's broadcasting makes this easier.

**Steps:**

1. Create a 1D tensor with 6 elements using `torch.arange()`

    - What does `torch.arange()` do and how is it different from `torch.tensor()`?

2. Reshape this 1D tensor into a 2x3 2D tensor using `.view()`

    - How does `.view()` compare to `.reshape()`? When might you use one over the other?

3. Create another 2x1 tensor with values [[1], [2]]

4. Add these tensors together using broadcasting

    - Think about: How does PyTorch determine which dimensions to broadcast?
    - Try to predict the output shape before running your code

In [2]:
# Your code for reshaping and broadcasting tensors

# --- Create 1D tensor with 6 elements ---
t = torch.arange(6)   # [0, 1, 2, 3, 4, 5]

# --- Reshape to 2x3 ---
t2 = t.view(2, 3)

# --- Create 2x1 tensor ---
b = torch.tensor([[1.0], [2.0]])

# --- Broadcasting addition ---
out = t2 + b

print("Original:", t)
print("Reshaped:\n", t2)
print("Broadcast tensor:\n", b)
print("Result:\n", out)
print("Result shape:", out.shape)

Original: tensor([0, 1, 2, 3, 4, 5])
Reshaped:
 tensor([[0, 1, 2],
        [3, 4, 5]])
Broadcast tensor:
 tensor([[1.],
        [2.]])
Result:
 tensor([[1., 2., 3.],
        [5., 6., 7.]])
Result shape: torch.Size([2, 3])


## Task 3: Move Tensors Between CPU and GPU
**Context:** Modern deep learning relies on GPU acceleration to process large datasets efficiently. Understanding how to move data between devices is essential for optimizing performance.

**Steps:**

1. Create a large tensor (1000x1000) on the CPU using `torch.rand()`

    - How does `torch.rand()` differ from `torch.randn()`?

2. Time how long it takes to square all values in this tensor on the CPU

    - Use the `time` module to measure execution time
    - Why use element-wise operations for testing performance differences?

3. Move your tensor to the GPU using `.to(device)`

    - What happens if you try to move to GPU on a system without one?

4. Time the same square operation on the GPU

    - Remember to include the time.time() calls before and after the operation

5. Compare and print the execution times

    - What factors might affect the performance difference you observe?

In [4]:
# Your code for comparing CPU and GPU performance

import time

# --- Create large tensor on CPU ---
cpu_tensor = torch.rand((1000, 1000))

# --- CPU timing ---
start = time.time()
cpu_squared = cpu_tensor ** 2
cpu_time = time.time() - start

print(f"CPU time: {cpu_time:.6f} seconds")

# --- Check GPU availability ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --- Move to GPU (if available) ---
gpu_tensor = cpu_tensor.to(device)

# --- GPU timing ---
start = time.time()
gpu_squared = gpu_tensor ** 2
gpu_time = time.time() - start

print(f"GPU time: {gpu_time:.6f} seconds")

CPU time: 0.003541 seconds
Using device: cuda
GPU time: 0.036629 seconds


## Task 4: Define Custom Functions and Utilize Autograd
**Context:** The ability to automatically compute gradients is essential for training neural networks. PyTorch's autograd system handles this complex task for you.

**Steps:**

1. Create a tensor with `requires_grad=True` to enable gradient tracking

    - Why do we need to set this flag for gradient computation?

2. Define a custom mathematical function (x³ + 2x²)

    - Consider how PyTorch builds a computation graph for this operation

3. Apply this function to your tensor

4. Call `.backward()` on the result to compute gradients

    - What does calling backward() do in PyTorch?
    - How is this related to backpropagation in neural networks?

5. Print the gradient values stored in `.grad` attribute of your input tensor

    - Check if the values match what you would expect from manual differentiation

In [5]:
# Your code for gradient computation

# --- Create tensor with gradient tracking ---
x = torch.tensor([2.0], requires_grad=True)

# --- Define function f(x) = x^3 + 2x^2 ---
f = x**3 + 2 * x**2

# --- Compute gradients ---
f.backward()

print("Input x:", x.item())
print("Gradient df/dx:", x.grad.item())

Input x: 2.0
Gradient df/dx: 20.0
